# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Module-Starter-PBP
version:      v0.0.3
version_from: lib/Module/Starter/PBP.pm
installdirs:  site
requires:
    Module::Starter:               0
    Test::More:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
